//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prosol.Core.ServiceReference2 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", ConfigurationName="ServiceReference2.z_servicemaster_com_srv")]
    public interface z_servicemaster_com_srv {
        
        // CODEGEN: Generating message contract since the operation Z_SERVICEMASTER_CREATE is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="urn:sap-com:document:sap:rfc:functions:z_servicemaster_com_srv:Z_SERVICEMASTER_CR" +
            "EATERequest", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Prosol.Core.ServiceReference2.Z_SERVICEMASTER_CREATEResponse1 Z_SERVICEMASTER_CREATE(Prosol.Core.ServiceReference2.Z_SERVICEMASTER_CREATERequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:sap-com:document:sap:rfc:functions:z_servicemaster_com_srv:Z_SERVICEMASTER_CR" +
            "EATERequest", ReplyAction="*")]
        System.Threading.Tasks.Task<Prosol.Core.ServiceReference2.Z_SERVICEMASTER_CREATEResponse1> Z_SERVICEMASTER_CREATEAsync(Prosol.Core.ServiceReference2.Z_SERVICEMASTER_CREATERequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class Z_SERVICEMASTER_CREATE : object, System.ComponentModel.INotifyPropertyChanged {
        
        private BAPIRET2[] zRETURNField;
        
        private ZASMDINPUT zSERVICEINPUTField;
        
        private BAPISRV_ASMDT[] zSERVICE_DESCRIPTIONField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public BAPIRET2[] ZRETURN {
            get {
                return this.zRETURNField;
            }
            set {
                this.zRETURNField = value;
                this.RaisePropertyChanged("ZRETURN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public ZASMDINPUT ZSERVICEINPUT {
            get {
                return this.zSERVICEINPUTField;
            }
            set {
                this.zSERVICEINPUTField = value;
                this.RaisePropertyChanged("ZSERVICEINPUT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public BAPISRV_ASMDT[] ZSERVICE_DESCRIPTION {
            get {
                return this.zSERVICE_DESCRIPTIONField;
            }
            set {
                this.zSERVICE_DESCRIPTIONField = value;
                this.RaisePropertyChanged("ZSERVICE_DESCRIPTION");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class BAPIRET2 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string tYPEField;
        
        private string idField;
        
        private string nUMBERField;
        
        private string mESSAGEField;
        
        private string lOG_NOField;
        
        private string lOG_MSG_NOField;
        
        private string mESSAGE_V1Field;
        
        private string mESSAGE_V2Field;
        
        private string mESSAGE_V3Field;
        
        private string mESSAGE_V4Field;
        
        private string pARAMETERField;
        
        private int rOWField;
        
        private string fIELDField;
        
        private string sYSTEMField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string TYPE {
            get {
                return this.tYPEField;
            }
            set {
                this.tYPEField = value;
                this.RaisePropertyChanged("TYPE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string NUMBER {
            get {
                return this.nUMBERField;
            }
            set {
                this.nUMBERField = value;
                this.RaisePropertyChanged("NUMBER");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string MESSAGE {
            get {
                return this.mESSAGEField;
            }
            set {
                this.mESSAGEField = value;
                this.RaisePropertyChanged("MESSAGE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string LOG_NO {
            get {
                return this.lOG_NOField;
            }
            set {
                this.lOG_NOField = value;
                this.RaisePropertyChanged("LOG_NO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string LOG_MSG_NO {
            get {
                return this.lOG_MSG_NOField;
            }
            set {
                this.lOG_MSG_NOField = value;
                this.RaisePropertyChanged("LOG_MSG_NO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string MESSAGE_V1 {
            get {
                return this.mESSAGE_V1Field;
            }
            set {
                this.mESSAGE_V1Field = value;
                this.RaisePropertyChanged("MESSAGE_V1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string MESSAGE_V2 {
            get {
                return this.mESSAGE_V2Field;
            }
            set {
                this.mESSAGE_V2Field = value;
                this.RaisePropertyChanged("MESSAGE_V2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string MESSAGE_V3 {
            get {
                return this.mESSAGE_V3Field;
            }
            set {
                this.mESSAGE_V3Field = value;
                this.RaisePropertyChanged("MESSAGE_V3");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string MESSAGE_V4 {
            get {
                return this.mESSAGE_V4Field;
            }
            set {
                this.mESSAGE_V4Field = value;
                this.RaisePropertyChanged("MESSAGE_V4");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string PARAMETER {
            get {
                return this.pARAMETERField;
            }
            set {
                this.pARAMETERField = value;
                this.RaisePropertyChanged("PARAMETER");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public int ROW {
            get {
                return this.rOWField;
            }
            set {
                this.rOWField = value;
                this.RaisePropertyChanged("ROW");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string FIELD {
            get {
                return this.fIELDField;
            }
            set {
                this.fIELDField = value;
                this.RaisePropertyChanged("FIELD");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string SYSTEM {
            get {
                return this.sYSTEMField;
            }
            set {
                this.sYSTEMField = value;
                this.RaisePropertyChanged("SYSTEM");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class BAPISRV_ASMDT : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string lANGUAGEField;
        
        private string lANGUAGE_ISOField;
        
        private string sHORT_TEXTField;
        
        private string cHANGE_IDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string LANGUAGE {
            get {
                return this.lANGUAGEField;
            }
            set {
                this.lANGUAGEField = value;
                this.RaisePropertyChanged("LANGUAGE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string LANGUAGE_ISO {
            get {
                return this.lANGUAGE_ISOField;
            }
            set {
                this.lANGUAGE_ISOField = value;
                this.RaisePropertyChanged("LANGUAGE_ISO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string SHORT_TEXT {
            get {
                return this.sHORT_TEXTField;
            }
            set {
                this.sHORT_TEXTField = value;
                this.RaisePropertyChanged("SHORT_TEXT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string CHANGE_ID {
            get {
                return this.cHANGE_IDField;
            }
            set {
                this.cHANGE_IDField = value;
                this.RaisePropertyChanged("CHANGE_ID");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZASMDINPUT : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string sERVICEField;
        
        private string dEL_INDField;
        
        private string mATL_GROUPField;
        
        private string bASE_UOMField;
        
        private string sERV_CATField;
        
        private string dIVISIONField;
        
        private string vAL_CLASSField;
        
        private string aUTH_GROUPField;
        
        private string tAX_INDField;
        
        private string fORMULAField;
        
        private string gRAPHIC_URLField;
        
        private string eAN_UPCField;
        
        private string eAN_CATField;
        
        private string sERV_TYPEField;
        
        private string eDITIONField;
        
        private string sSC_ITEMField;
        
        private string hIER_SERVField;
        
        private string wAGETYPEField;
        
        private string p_STATUSField;
        
        private string vALID_FROMField;
        
        private decimal cONV_DENField;
        
        private decimal cONV_NUMField;
        
        private string cHGTEXTField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string SERVICE {
            get {
                return this.sERVICEField;
            }
            set {
                this.sERVICEField = value;
                this.RaisePropertyChanged("SERVICE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string DEL_IND {
            get {
                return this.dEL_INDField;
            }
            set {
                this.dEL_INDField = value;
                this.RaisePropertyChanged("DEL_IND");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string MATL_GROUP {
            get {
                return this.mATL_GROUPField;
            }
            set {
                this.mATL_GROUPField = value;
                this.RaisePropertyChanged("MATL_GROUP");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string BASE_UOM {
            get {
                return this.bASE_UOMField;
            }
            set {
                this.bASE_UOMField = value;
                this.RaisePropertyChanged("BASE_UOM");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string SERV_CAT {
            get {
                return this.sERV_CATField;
            }
            set {
                this.sERV_CATField = value;
                this.RaisePropertyChanged("SERV_CAT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string DIVISION {
            get {
                return this.dIVISIONField;
            }
            set {
                this.dIVISIONField = value;
                this.RaisePropertyChanged("DIVISION");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string VAL_CLASS {
            get {
                return this.vAL_CLASSField;
            }
            set {
                this.vAL_CLASSField = value;
                this.RaisePropertyChanged("VAL_CLASS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string AUTH_GROUP {
            get {
                return this.aUTH_GROUPField;
            }
            set {
                this.aUTH_GROUPField = value;
                this.RaisePropertyChanged("AUTH_GROUP");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string TAX_IND {
            get {
                return this.tAX_INDField;
            }
            set {
                this.tAX_INDField = value;
                this.RaisePropertyChanged("TAX_IND");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string FORMULA {
            get {
                return this.fORMULAField;
            }
            set {
                this.fORMULAField = value;
                this.RaisePropertyChanged("FORMULA");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string GRAPHIC_URL {
            get {
                return this.gRAPHIC_URLField;
            }
            set {
                this.gRAPHIC_URLField = value;
                this.RaisePropertyChanged("GRAPHIC_URL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string EAN_UPC {
            get {
                return this.eAN_UPCField;
            }
            set {
                this.eAN_UPCField = value;
                this.RaisePropertyChanged("EAN_UPC");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string EAN_CAT {
            get {
                return this.eAN_CATField;
            }
            set {
                this.eAN_CATField = value;
                this.RaisePropertyChanged("EAN_CAT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string SERV_TYPE {
            get {
                return this.sERV_TYPEField;
            }
            set {
                this.sERV_TYPEField = value;
                this.RaisePropertyChanged("SERV_TYPE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public string EDITION {
            get {
                return this.eDITIONField;
            }
            set {
                this.eDITIONField = value;
                this.RaisePropertyChanged("EDITION");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public string SSC_ITEM {
            get {
                return this.sSC_ITEMField;
            }
            set {
                this.sSC_ITEMField = value;
                this.RaisePropertyChanged("SSC_ITEM");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public string HIER_SERV {
            get {
                return this.hIER_SERVField;
            }
            set {
                this.hIER_SERVField = value;
                this.RaisePropertyChanged("HIER_SERV");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=17)]
        public string WAGETYPE {
            get {
                return this.wAGETYPEField;
            }
            set {
                this.wAGETYPEField = value;
                this.RaisePropertyChanged("WAGETYPE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=18)]
        public string P_STATUS {
            get {
                return this.p_STATUSField;
            }
            set {
                this.p_STATUSField = value;
                this.RaisePropertyChanged("P_STATUS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=19)]
        public string VALID_FROM {
            get {
                return this.vALID_FROMField;
            }
            set {
                this.vALID_FROMField = value;
                this.RaisePropertyChanged("VALID_FROM");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=20)]
        public decimal CONV_DEN {
            get {
                return this.cONV_DENField;
            }
            set {
                this.cONV_DENField = value;
                this.RaisePropertyChanged("CONV_DEN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=21)]
        public decimal CONV_NUM {
            get {
                return this.cONV_NUMField;
            }
            set {
                this.cONV_NUMField = value;
                this.RaisePropertyChanged("CONV_NUM");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=22)]
        public string CHGTEXT {
            get {
                return this.cHGTEXTField;
            }
            set {
                this.cHGTEXTField = value;
                this.RaisePropertyChanged("CHGTEXT");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class Z_SERVICEMASTER_CREATEResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private BAPIRET2[] zRETURNField;
        
        private string zSERVICEField;
        
        private BAPISRV_ASMDT[] zSERVICE_DESCRIPTIONField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public BAPIRET2[] ZRETURN {
            get {
                return this.zRETURNField;
            }
            set {
                this.zRETURNField = value;
                this.RaisePropertyChanged("ZRETURN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string ZSERVICE {
            get {
                return this.zSERVICEField;
            }
            set {
                this.zSERVICEField = value;
                this.RaisePropertyChanged("ZSERVICE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public BAPISRV_ASMDT[] ZSERVICE_DESCRIPTION {
            get {
                return this.zSERVICE_DESCRIPTIONField;
            }
            set {
                this.zSERVICE_DESCRIPTIONField = value;
                this.RaisePropertyChanged("ZSERVICE_DESCRIPTION");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Z_SERVICEMASTER_CREATERequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        public Prosol.Core.ServiceReference2.Z_SERVICEMASTER_CREATE Z_SERVICEMASTER_CREATE;
        
        public Z_SERVICEMASTER_CREATERequest() {
        }
        
        public Z_SERVICEMASTER_CREATERequest(Prosol.Core.ServiceReference2.Z_SERVICEMASTER_CREATE Z_SERVICEMASTER_CREATE) {
            this.Z_SERVICEMASTER_CREATE = Z_SERVICEMASTER_CREATE;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Z_SERVICEMASTER_CREATEResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        public Prosol.Core.ServiceReference2.Z_SERVICEMASTER_CREATEResponse Z_SERVICEMASTER_CREATEResponse;
        
        public Z_SERVICEMASTER_CREATEResponse1() {
        }
        
        public Z_SERVICEMASTER_CREATEResponse1(Prosol.Core.ServiceReference2.Z_SERVICEMASTER_CREATEResponse Z_SERVICEMASTER_CREATEResponse) {
            this.Z_SERVICEMASTER_CREATEResponse = Z_SERVICEMASTER_CREATEResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface z_servicemaster_com_srvChannel : Prosol.Core.ServiceReference2.z_servicemaster_com_srv, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class z_servicemaster_com_srvClient : System.ServiceModel.ClientBase<Prosol.Core.ServiceReference2.z_servicemaster_com_srv>, Prosol.Core.ServiceReference2.z_servicemaster_com_srv {
        
        public z_servicemaster_com_srvClient() {
        }
        
        public z_servicemaster_com_srvClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public z_servicemaster_com_srvClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public z_servicemaster_com_srvClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public z_servicemaster_com_srvClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Prosol.Core.ServiceReference2.Z_SERVICEMASTER_CREATEResponse1 Prosol.Core.ServiceReference2.z_servicemaster_com_srv.Z_SERVICEMASTER_CREATE(Prosol.Core.ServiceReference2.Z_SERVICEMASTER_CREATERequest request) {
            return base.Channel.Z_SERVICEMASTER_CREATE(request);
        }
        
        public Prosol.Core.ServiceReference2.Z_SERVICEMASTER_CREATEResponse Z_SERVICEMASTER_CREATE(Prosol.Core.ServiceReference2.Z_SERVICEMASTER_CREATE Z_SERVICEMASTER_CREATE1) {
            Prosol.Core.ServiceReference2.Z_SERVICEMASTER_CREATERequest inValue = new Prosol.Core.ServiceReference2.Z_SERVICEMASTER_CREATERequest();
            inValue.Z_SERVICEMASTER_CREATE = Z_SERVICEMASTER_CREATE1;
            Prosol.Core.ServiceReference2.Z_SERVICEMASTER_CREATEResponse1 retVal = ((Prosol.Core.ServiceReference2.z_servicemaster_com_srv)(this)).Z_SERVICEMASTER_CREATE(inValue);
            return retVal.Z_SERVICEMASTER_CREATEResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Prosol.Core.ServiceReference2.Z_SERVICEMASTER_CREATEResponse1> Prosol.Core.ServiceReference2.z_servicemaster_com_srv.Z_SERVICEMASTER_CREATEAsync(Prosol.Core.ServiceReference2.Z_SERVICEMASTER_CREATERequest request) {
            return base.Channel.Z_SERVICEMASTER_CREATEAsync(request);
        }
        
        public System.Threading.Tasks.Task<Prosol.Core.ServiceReference2.Z_SERVICEMASTER_CREATEResponse1> Z_SERVICEMASTER_CREATEAsync(Prosol.Core.ServiceReference2.Z_SERVICEMASTER_CREATE Z_SERVICEMASTER_CREATE) {
            Prosol.Core.ServiceReference2.Z_SERVICEMASTER_CREATERequest inValue = new Prosol.Core.ServiceReference2.Z_SERVICEMASTER_CREATERequest();
            inValue.Z_SERVICEMASTER_CREATE = Z_SERVICEMASTER_CREATE;
            return ((Prosol.Core.ServiceReference2.z_servicemaster_com_srv)(this)).Z_SERVICEMASTER_CREATEAsync(inValue);
        }
    }
}
